### ISSUE TITLE
The driver for Wifi module(MT6625) is not available

### ISSUE THREAD

**Issue by garywangcn** [BPI-SINOVOIP/BPI-R2-bsp#1]
On R2 board, there is an onboard WIFI module MT6625, but right now the driver for it is not available.

**Comment by garywangcn** [comment]
We are working with vendor to debug MT6625 driver, now this driver is almost readby and we're testing the its stability.

**Comment by androidbftab1** [comment]
Now the wifi driver is working fine at 2.4G, and we're debugging the 5G and testing its performance. 
Below file is an instruction for how to enable WIFI module on R2:
https://github.com/BPI-SINOVOIP/BPI-R2-bsp/blob/Wifi_debug_branch/vendor/mediatek/connectivity/readme

And please use the following command to connect a wifi AP:
1. wpa_passphrase "yyy" "xxxxx" >/etc/wpa_supplicant.conf
2. vim /etc//etc/wpa_supplicant.conf
/etc/wpa_supplicant.conf
network={
        ssid="yyy"
        key_mgmt=WPA-PSK
        proto=WPA2
        pairwise=CCMP
        group=CCMP
        #psk="xxxxx"
        psk=90e3ac2dd8a92432f31d65e4f3297962ede273e85a5c4407ee4f7ffc052fd8bb
}

3. /sbin/wpa_supplicant -i wlan0 -B -c /etc/wpa_supplicant.conf
4. dhclient wlan0

**Comment by garywangcn** [comment]
Below is the performance of WIFI:


WIFI   Test(5G)
--
Direction | Speed |   |  
R2(wireless)   -> PC(wired) | 34.2 Mbits/sec |   |  
R2(wireless)   <- PC(wired) | 87.2 Mbits/sec |   |  
R2(wireless)   <-> PC(wired) | PC->R2   : 83.9 Mbits/sec     R2->PC : 348 Kbits/sec |   |  
  |   |   |  
  |   |   |  
  |   |   |  
  |   |   |  
WIFI Test(2.4G)
Direction | Speed |   |  
R2(wireless)   -> PC(wired) | 16.2 Mbits/sec |   |  
R2(wireless)   <- PC(wired) | 31.6 Mbits/sec |   |  
R2(wireless)   <-> PC(wired) | PC->R2   : 24.2 Mbits/sec     R2->PC : 9.06 Mbits/sec |   |  

Looks like the TX/RX balance under 5G is bad.

**Comment by garywangcn** [comment]
The commit https://github.com/BPI-SINOVOIP/BPI-R2-bsp/commit/cdf38bc6518cce5c01c35e0d5241bab96ba7d652 is to support 5G. If you want to try it, please copy the file WIFI under vendor/mediatek/connectivity/firmware/nvram to /etc/firmware/nvram of R2 file system.

**Comment by frank-w** [comment]
are you working also on AP-mode?

**Comment by garywangcn** [comment]
The code for supporting WIFI module(MT6625) is merged to master branch, will test it later.

**Comment by garywangcn** [comment]
The code for supporting WIFI is merged to master branch with tag v1.2.0
