### ISSUE TITLE
Update mt7623.dtsi to support multiple uart and GPIO

### ISSUE THREAD

**Issue by frank-w** [BPI-SINOVOIP/BPI-R2-bsp#11]
http://elixir.free-electrons.com/linux/v4.13-rc7/source/arch/arm/boot/dts/mt7623.dtsi

**Comment by garywangcn** [comment]
Thanks frank.

The GPIO is supported in current code(dts),  but the uart0,1 and 3 are not added in dts, if we need them, please add the following lines to mt7623.dtsi and rebuild the kernel.

	uart0: serial@11002000 {
		compatible = "mediatek,mt7623-uart",
			     "mediatek,mt6577-uart";
		reg = <0 0x11002000 0 0x400>;
		interrupts = <GIC_SPI 51 IRQ_TYPE_LEVEL_LOW>;
		clocks = <&pericfg CLK_PERI_UART0_SEL>,
			 <&pericfg CLK_PERI_UART0>;
		clock-names = "baud", "bus";
		status = "disabled";
	};

	uart1: serial@11003000 {
		compatible = "mediatek,mt7623-uart",
			     "mediatek,mt6577-uart";
		reg = <0 0x11003000 0 0x400>;
		interrupts = <GIC_SPI 52 IRQ_TYPE_LEVEL_LOW>;
		clocks = <&pericfg CLK_PERI_UART1_SEL>,
			 <&pericfg CLK_PERI_UART1>;
		clock-names = "baud", "bus";
		status = "disabled";
	};

	uart3: serial@11005000 {
		compatible = "mediatek,mt7623-uart",
			     "mediatek,mt6577-uart";
		reg = <0 0x11005000 0 0x400>;
		interrupts = <GIC_SPI 54 IRQ_TYPE_LEVEL_LOW>;
		clocks = <&pericfg CLK_PERI_UART3_SEL>,
			 <&pericfg CLK_PERI_UART3>;
		clock-names = "baud", "bus";
		status = "disabled";
	};

**Comment by garywangcn** [comment]
I'd like to close this ticket, is it okay? @frank-w

**Comment by frank-w** [comment]
I'd like to enanle at least 1 uart additionally to log-port. Are there Problems if it's enabled?
are the other gpio working?

**Comment by garywangcn** [comment]
All GPIO-s are working fine, there is a script to control GPIO:
SYS_FILE=/sys/devices/platform/1000b000.pinctrl/mt_gpio

mt_gpio_mode()
{
   pin=$1
   mode=$2
  
   if [ ! -f ${SYS_FILE} ]; then
       exit 1
   fi

   echo "mode $pin $mode" > ${SYS_FILE}

   return 0   
}

mt_gpio_dir()
{
   pin=$1
   dir=$2
 
   if [ "x${dir}" == "xout" ]; then
       dir_val=1
   else
       dir_val=0
   fi
 
   if [ ! -f ${SYS_FILE} ]; then
       exit 1
   fi

   echo "dir $pin $dir_val" > ${SYS_FILE}

   return 0   
}

mt_gpio_out()
{
   pin=$1
   out=$2
 
   if [ ! -f ${SYS_FILE} ]; then
       exit 1
   fi

   echo "out $pin $out" > ${SYS_FILE}

   return 0   
}

mt_gpio_in()
{
   pin=$1
 
   if [ ! -f ${SYS_FILE} ]; then
       exit 1
   fi

   echo "start $1" > ${SYS_FILE}
   result=`cat ${SYS_FILE} | grep "$1"`

   if [ "x${result}" == "x" ]; then
       echo "can't get $pin status"
       exit 2
   fi

   pin_val=`echo ${result} | awk -F ' |-' '{print $5}'`
   if [ ${pin_val} == "0" ] ; then
       return 0
   else
       return 1
   fi
  
   return 0

}

For GPIO22/GPIO23/GPIO24, we need to set EINTx_BOND_DIS to 1.

![image](https://user-images.githubusercontent.com/22828078/30032422-73f3dc96-91c8-11e7-9cb1-3230818b3953.png)

**Comment by frank-w** [comment]
Thx for the info,hoping wiringpi will be ported too
is there any Problem,when enabling uart0/1/3?
In your dtsi-code it seems that every uart need 1 SPI-port. On https://bananapi.gitbooks.io/banana-pi-bpi-r2-open-source-smart-router/content/bpi-r2-gpio-pin-define.html i see only 1 uart (which is it) not affecting any other protocol

Regards frank

**Comment by frank-w** [comment]
looked in shematics (page 19)...Uart1 seems to be the gpio-uart (pin 8+10), uart0 is pin 11+13 ( gpio 17+27 not shown as uart). i have not found uart3 yet
