### ISSUE TITLE
Bug in init of ethernet driver?

### ISSUE THREAD

**Issue by andreas74a** [BPI-SINOVOIP/BPI-R2-bsp#21]
Hello,

I'm not the big kernel developer, but I saw in
https://github.com/torvalds/linux/blob/master/drivers/net/ethernet/mediatek/mtk_eth_soc.c
the following code:
```
static int __init mtk_init(struct net_device *dev)
{
	struct mtk_mac *mac = netdev_priv(dev);
	struct mtk_eth *eth = mac->hw;
	const char *mac_addr;

	mac_addr = of_get_mac_address(mac->of_node);
	if (mac_addr)
		ether_addr_copy(dev->dev_addr, mac_addr);

	/* If the mac address is invalid, use random mac address  */
	if (!is_valid_ether_addr(dev->dev_addr)) {
		eth_hw_addr_random(dev);
		dev_err(eth->dev, "generated random MAC address %pM\n",
			dev->dev_addr);
	}

	return mtk_phy_connect(dev);
}
```
and I wonder, the function ether_addr_copy wants to copy the content from dev->dev_addr to mac_addr. Is this the plan? I have the feeling, that the parameters should be changed?

Kind regards, Andreas

**Comment by JackZengBpi** [comment]
thanks for your notification @andreas74a ;
actually, the function prototype is “ static inline void ether_addr_copy(u8 *dst, const u8 *src) ”,
so, **ether_addr_copy** will copy the content from **mac_addr** to **dev->dev_addr**.

**Comment by andreas74a** [comment]
Okay, my mistake. Somehow I landed at this page
http://dpdk.org/doc/api/rte__ether_8h.html#a38a0c494f25e8d352ba382a9e3e806b7
but this has nothing to do with the linux kernel.

Sorry

**Comment by JackZengBpi** [comment]
it's ok, thanks for your comments, if you have any advice or questions , welcome to discuss in forum, and I'm glad to communicate with you! @andreas74a
