### ISSUE TITLE
is it i2s or i2c?

### ISSUE THREAD

**Issue by frank-w** [BPI-SINOVOIP/BPI-R2-bsp#22]
https://github.com/BPI-SINOVOIP/BPI-R2-bsp/blob/1277662570697fd0038ef5c58e5782c0e3f7e965/linux-mt/arch/arm/boot/dts/mt7623n-bpi-r2.dts#L130

because of codec it should be i2s...i2c 0 and 1 should be on GPIO, right?

**Comment by garywangcn** [comment]
For I2S chip, an additional I2C interface is required to read/write registers, so the I2C pin should be work as I2C.

**Comment by frank-w** [comment]
ok,is that really i2c1? i ask because on gpio there is i2c0 (pins 3+5) and i2c1 (pins 27+28). if i2c1 is used for communication to audio-chip, there must be master/slave for it if someone will use i2c1 on gpio

**Comment by frank-w** [comment]
on BPI-R2 there is no audio: 
http://forum.banana-pi.org/t/has-anyone-added-an-rtc/5004/11
