### ISSUE TITLE
unable to disable tx-checksum-ipv4 for both eth0 and eth1

### ISSUE THREAD

**Issue by garywangcn** [BPI-SINOVOIP/BPI-R2-bsp#23]
See below image for details.

![ldz3_20jl9jv w 8o 4 6kg](https://user-images.githubusercontent.com/22828078/34663140-2e0e43f8-f490-11e7-8486-005b05fffe57.jpg)

**Comment by garywangcn** [comment]
Patch for this issue:
root@:/work/BPI-R2-bsp# git diff linux-mt/drivers/net/ethernet/mediatek/mtk_eth_soc.c
diff --git a/linux-mt/drivers/net/ethernet/mediatek/mtk_eth_soc.c b/linux-mt/drivers/net/ethernet/mediatek/mtk_eth_soc.c
index e20b04a..d5404a7 100644
--- a/linux-mt/drivers/net/ethernet/mediatek/mtk_eth_soc.c
+++ b/linux-mt/drivers/net/ethernet/mediatek/mtk_eth_soc.c
@@ -2011,6 +2011,9 @@ static int mtk_add_mac(struct mtk_eth *eth, struct device_node *np)
                ~(NETIF_F_HW_VLAN_CTAG_TX | NETIF_F_HW_VLAN_CTAG_RX);
        eth->netdev[id]->features |= MTK_HW_FEATURES;
        eth->netdev[id]->features  &= ~NETIF_F_GSO;
+
+        /* Set user-changeable features (subset of all device features) */
+       eth->netdev[id]->hw_features = eth->netdev[id]->features;
        eth->netdev[id]->ethtool_ops = &mtk_ethtool_ops;
 
        eth->netdev[id]->irq = eth->irq[0];

**Comment by frank-w** [comment]
@garywangcn. Can ypu put the patch in codeblock or attach as file to make it better readable?

**Comment by JackZengBpi** [comment]
This issue is fixed by fa363e4, so close this issue.

**Comment by JackZengBpi** [comment]
This issue is fixed by fa363e4, so close this issue.
