### ISSUE TITLE
Environment of u-boot won't save in sd cart when boot from external sd card.

### ISSUE THREAD

**Issue by WeiqiChenCN** [BPI-SINOVOIP/BPI-R2-bsp#28]
I testd, and with a switch on board, I can boot uboot from internal emmc and external sd card ( cold start-up ).
It would be nice that it load/save environment in external sd card when it boot from external media. For example, u-boot can detect the status of the __boot switch__ on board to do that.

**Comment by JackZengBpi** [comment]
Hello, Chen :
this function I have finished it，after I tested it，it will be released for the next time.

**Comment by garywangcn** [comment]
Hi Jack

is this issue closed, right?

**Comment by JackZengBpi** [comment]
yes，Gary，you can close it now.
