### ISSUE TITLE
What's the maximum size for the SD card

### ISSUE THREAD

**Issue by symsymmas** [BPI-SINOVOIP/BPI-R2-bsp#38]
Hello,

Is there a size limit for my SD card to work with Banana Pi?

Sincerely,

**Comment by symsymmas** [comment]
It seems like 256GB works with it (https://www.cnx-software.com/2017/01/03/banana-pi-bpi-r2-router-board-powered-by-mediatek-mt7623a-quad-core-processor-comes-with-5-gbe-ports-sata-and-more/).

**Comment by brutspark** [comment]
@symsymmas i try 64gb sd card works well, hope more also
