### ISSUE TITLE
Preloader's uboot load size

### ISSUE THREAD

**Issue by rayddteam** [BPI-SINOVOIP/BPI-R2-bsp#39]
U-Boot partition size is 0x80000, but preloader copy only 300000 (0x0493e0).
So modern U-Boot (2019-07) can't be used with additional options.

Displayed correct:
[PART]partition name UBOOT
[PART]partition start block 0x200
[PART]partition size 0x80000
[PART]partition blks 0x400

Please change preloaders copy size to whole part size (0x80000).

**Comment by rayddteam** [comment]
Fixed in https://github.com/BPI-SINOVOIP/BPI-files/commit/46aebefd64b464d5aa4d64fa6583077ce8d020b7
Thanks for support!

**Comment by frank-w** [comment]
please fix in SD-Card preloader too

edit: seems you have rebased your repo...

https://github.com/BPI-SINOVOIP/BPI-files/commit/fd375fec05e12e450c58c9606c59e5f3883aa5ca

contains both preloaders now
