### ISSUE TITLE
build.sh does not check for success

### ISSUE THREAD

**Issue by frank-w** [BPI-SINOVOIP/BPI-R2-bsp#8]
...
"mkimage" command not found - U-Boot images will not be built
arch/arm/boot/Makefile:92: die Regel für Ziel „arch/arm/boot/uImage“ scheiterte
make[2]: *** [arch/arm/boot/uImage] Fehler 1
arch/arm/Makefile:329: die Regel für Ziel „uImage“ scheiterte
make[1]: *** [uImage] Fehler 2
make[1]: Verzeichnis „/home/frank/bpi-r2/BPI-R2-bsp/linux-mt“ wird verlassen
Makefile:50: die Regel für Ziel „kernel“ scheiterte
make: *** [kernel] Fehler 2

 Build success!

build.sh:
echo -e "\033[31m Build success!\033[0m"

without check for return-codes

**Comment by frank-w** [comment]
added simple check for Option #1 
can't push to github currently (i think i must be invited)
[build.sh.zip](https://github.com/BPI-SINOVOIP/BPI-R2-bsp/files/1254516/build.sh.zip)

**Comment by frank-w** [comment]
for the base problem (mkimage not found) i have to execute:
"sudo apt-get install u-boot-tools"

...just for the readme :)

**Comment by garywangcn** [comment]
Thanks for your suggestion, I will add your changes to github.

**Comment by frank-w** [comment]
Thanks if you give me push-rights i can it change self.
i also think a note before asking sudo-pw (scriptname + information about action require sudo) is helpful. As i see lo-device is created and written. Maybe some information on how to get the files on sd-card is also helpful after build is finished

**Comment by garywangcn** [comment]
https://github.com/BPI-SINOVOIP/BPI-R2-bsp/commit/81776dada7beacfe4efbe3fbb16fbf909f94fe2e

This issue is fixed, so close this ticket.
