### ISSUE TITLE
u-boot: BPI-R2 ignore power button if SD card not inserted.

### ISSUE THREAD

**Issue by rayddteam** [BPI-SINOVOIP/BPI-R2-bsp#9]
I copied data from SD card into eMMC. It works fine, but only if SD card inserted (I removing SD card while board still in u-boot).
Maybe I need to copy u-boot separately?

**Comment by garywangcn** [comment]
Can you please share us the console log while SD is removed? Also, please let me know what commands you'are executed to copy data from SD card into eMMC?

Thanks

**Comment by rayddteam** [comment]
Just silence. It completely ignore power button press.
I did `dd bs=1m if=/dev/mmcblk0 of=/dev/mmcblk1`
Maybe I need to copy u-boot somewhere else?

**Comment by garywangcn** [comment]
@rayddteam I will do some tests with the command you provided,

**Comment by garywangcn** [comment]
@rayddteam 
can you please have the try with the following steps:
How to boot from eMMC:
  1. boot from SD
  2. sudo su
  3. echo 0 > /sys/block/mmcblk1boot0/force_ro #enable /dev/mmcblk1boot0 write mode
  4. To write preloader to EMMC by running command:
            bpi-bootsel -d /dev/mmcblk1boot0 BPI-R2-EMMC-boot0-DDR1600-0k-0905.img.gz
  5. To copy ubuntu image to EMMC:
            unzip -p <XXX.img.zip> | pv | dd of=<device> bs=10M status=noxfer
            where the XXX.img.zip is ubuntu image we can get it from http://www.banana-pi.org/r2-download.html , and where <device> should be /dev/mmcblk1.
  6. poweroff
  7. remove SD & power on

**Comment by rayddteam** [comment]
Ahh, so first level bootloader support boot from only one mmc.
Will try.
Since it may contain boot key, I'm not asking its source code, but have to ask: is it planning to make dual-boot one?

**Comment by fgheorghe** [comment]
Hi Gary, thank you for your reply - I tried these instructions to no luck - it just ignores the boot (RGB LEDs stay on, no other LED flashes)

**Comment by garywangcn** [comment]
Hi fgheorghe

I'm assuming you are trying to boot the ubuntu image from emmc, and you have copied the ubuntu image and preloader to emmc, right? 
If yes, can you please share me the console log of copying ubuntu image and preloader to emmc?

**Comment by fgheorghe** [comment]
Hi gary - indeed, I am copying the image as per your instructions. I will have to fetch the log now as I turned the device off - but everything seemed to be successful. Will get back to you later on once I redoit.

**Comment by fgheorghe** [comment]
Hi Gary, I've noticed i'm getting an out of disk space error when running these commands against the latest ubuntu mate:

root@bpi-iot-ros-ai:/home/pi# ls
2017-09-04-ubuntu-16.04-mate-desktop-bpi-r2-sd-emmc-v1.2.0.img.zip
root@bpi-iot-ros-ai:/home/pi# echo 0 > /sys/block/mmcblk1boot0/force_ro
root@bpi-iot-ros-ai:/home/pi# bpi-bootsel -d /dev/mmcblk1boot0 BPI-R2-EMMC-boot0-DDR1600-0k-0905.img.gz
DEVICE=/dev/mmcblk1boot0
Warning: Try to write  to BOOTDISK /dev/mmcblk1boot0
INFO: /dev/mmcblk1boot0 : SD/eMMC !!
umount device: /dev/mmcblk1boot0

##########################
# Burning the bootloader #
##########################

Wait for download BPI-R2-EMMC-boot0-DDR1600-0k-0905.img.gz ...
https://github.com/BPI-SINOVOIP/BPI-files/raw/master/SD/100MB/BPI-R2-EMMC-boot0-DDR1600-0k-0905.img.gz
OK!!\n
sudo gunzip -c BPI-R2-EMMC-boot0-DDR1600-0k-0905.img.gz | dd of=/dev/mmcblk1boot0 bs=1024 seek=0
92+1 records in
92+1 records out
94720 bytes (95 kB) copied, 0.111476 s, 850 kB/s
OK!! You can remove the BOOTDISK /dev/mmcblk1boot0 now!!
root@bpi-iot-ros-ai:/home/pi# unzip -p 2017-09-04-ubuntu-16.04-mate-desktop-bpi-r2-sd-emmc-v1.2.0.img.zip  | pv | dd of=/dev/mmcblk1
mmcblk1       mmcblk1boot0  mmcblk1boot1  mmcblk1p1     mmcblk1p2     mmcblk1rpmb   
root@bpi-iot-ros-ai:/home/pi# unzip -p 2017-09-04-ubuntu-16.04-mate-desktop-bpi-r2-sd-emmc-v1.2.0.img.zip  | pv | dd of=/dev/mmcblk1 bs=10M status=noxfer
dd: error writing ‘/dev/mmcblk1’: No space left on device                                                                                                                 <=>                                         ]
7.28GiB 0:18:59 [6.54MiB/s] [                                                                                                                                                 <=>                                     ]
0+64165 records in
0+64164 records out
root@bpi-iot-ros-ai:/home/pi#

**Comment by fgheorghe** [comment]
I managed to get my hands onto a serial cable, here is what u-boot shows when booting from emmc:

MMC read: dev # 0, block # 2560, count 0 ... 0 blocks read: OK
serious check
Bad Magic Number.

**Comment by garywangcn** [comment]
Hi fgheorghe

According to the log you provided, the preloader is wrote successfully, I will test this command "unzip -p 2017-09-04-ubuntu-16.04-mate-desktop-bpi-r2-sd-emmc-v1.2.0.img.zip | pv | dd of=/dev/mmcblk1 bs=10M status=noxfer" to see what problem happens.

And maybe you can use the workaround "dd if=/dev/mmcblk0 of=/dev/mmcblk1" to copy ubuntu image from SD to EMMC when the ubuntu system is booting from SD, this may cause other problem about the file system of EMMC, need to run fsck to correct it when you boot it from EMMC.

**Comment by garywangcn** [comment]
Hi fgheorghe

I tried above steps again on my board( for step 5, the command is "bpi-copy 2017-09-04-ubuntu-16.04-mate-desktop-bpi-r2-sd-emmc-v1.2.0.img.zip /dev/mmcblk1"), don't see any problem.

**Comment by dfiloni** [comment]
I can confirm this issue, when I power on the board again after the copy, (without the SD) it doesn't boot at all. Red, green and blue leds are on and there is no output on the serial port.

**Comment by garywangcn** [comment]
@rayddteam @dfiloni @fgheorghe 

I'm sorry for my late response, please follow below instructions to do fix it:

I think this problem is cuased by the wrong partition configuration, please follow below steps to correct it(please note that the ubuntu image on emmc will be damaged):

1.install the SD card with LEDE test image, we can get the image from link http://pan.baidu.com/s/1eS1pRCA, also more information about this image in link http://forum.banana-pi.org/t/bpi-r2-new-image-openwrt-lede-2017-09-08/3797

2. Power on the R2 board,

3. After the u-boot prompt "BPI-R2>" appears, please enter the command "emmc ecsd" to check partition configuration, on your board, the partition configuration should be 0h

[EXT_CSD] Partition config : 0h

4. Then run command "emmc pconf 0x48" to change it

5. Power off this board, remove SD card, and then power it on, the board will boot with lede test image which is stored in EMMC.

6. The ubuntu system you programmed to EMMC has been damaged yet, need to re-program it, so sorry for this.

Please let me know if you have any question......

**Comment by dfiloni** [comment]
@garywangcn : it worked for me. Is there a way to fix it in uboot code without having to do above steps in all devices? Thank you!

**Comment by fgheorghe** [comment]
Hi Gary,

No worries, will run it asap. 

Regards,
Flaviu

**Comment by fgheorghe** [comment]
Now I am getting this:

BPI-IoT> emmc ecsd
Unknown command 'emmc' - try 'help'
BPI-IoT> 

Notice it doesn't show BPI-R2, it shows BPI-IoT

**Comment by fgheorghe** [comment]
Here is the full boot log: 

[USBD] USB PRB0 LineState: 0

[USBD] USB cable/ No Cable inserted!

[PLFM] Keep stay in USB Mode
Platform initialization is ok
wait for frequency meter finish, CLK26CALI = 0x81
mt_pll_post_init: mt_get_cpu_freq = 1040000Khz
wait for frequency meter finish, CLK26CALI = 0x90
mt_pll_post_init: mt_get_bus_freq = 273000Khz
wait for frequency meter finish, CLK26CALI = 0x81
mt_pll_post_init: mt_get_mem_freq = 133250Khz
[PWRAP] pwrap_init_preloader
[PWRAP] pwrap_init
[PWRAP] _pwrap_init_sistrobe [Read Test] fail,index=0,rdata=2D52
[PWRAP] _pwrap_init_sistrobe [Read Test] fail,index=1,rdata=2D52
[PWRAP] _pwrap_init_sistrobe [Read Test] fail,index=2,rdata=2D52
[PWRAP] _pwrap_init_sistrobe [Read Test] pass,index=3 rdata=5AA5
[PWRAP] _pwrap_init_sistrobe [Read Test] pass,index=4 rdata=5AA5
[PWRAP] _pwrap_init_sistrobe [Read Test] pass,index=5 rdata=5AA5
[PWRAP] _pwrap_init_sistrobe [Read Test] pass,index=6 rdata=5AA5
[PWRAP] _pwrap_init_sistrobe [Read Test] pass,index=7 rdata=5AA5
[PWRAP] _pwrap_init_sistrobe [Read Test] pass,index=8 rdata=5AA5
[PWRAP] _pwrap_init_sistrobe [Read Test] pass,index=9 rdata=5AA5
[PWRAP] _pwrap_init_sistrobe [Read Test] pass,index=10 rdata=5AA5
[PWRAP] _pwrap_init_sistrobe [Read Test] fail,index=11,rdata=B54B
[PWRAP] _pwrap_init_sistrobe [Read Test] fail,index=12,rdata=B54B
[PWRAP] _pwrap_init_sistrobe [Read Test] fail,index=13,rdata=B54B
[PWRAP] _pwrap_init_sistrobe [Read Test] fail,index=14,rdata=B54B
[PWRAP] _pwrap_init_sistrobe [Read Test] fail,index=15,rdata=B54B
[PWRAP] _pwrap_init_sistrobe [Read Test] fail,index=16,rdata=B54B
[PWRAP] _pwrap_init_sistrobe [Read Test] fail,index=17,rdata=B54B
[PWRAP] _pwrap_init_sistrobe [Read Test] fail,index=18,rdata=B54B
[PWRAP] _pwrap_init_sistrobe [Read Test] fail,index=19,rdata=6A97
[PWRAP] _pwrap_init_sistrobe [Read Test] fail,index=20,rdata=6A97
[PWRAP] _pwrap_init_sistrobe [Read Test] fail,index=21,rdata=6A97
[PWRAP] _pwrap_init_sistrobe [Read Test] fail,index=22,rdata=6A97
[PWRAP] _pwrap_init_sistrobe [Read Test] fail,index=23,rdata=6A97
[PWRAP] _pwrap_init_reg_clock
[PMIC_WRAP]wrap_init pass,the return value=0.
[pmic6323_init] Preloader Start..................
[pmic6323_init] PMIC CHIP Code = 0x2023
INT_MISC_CON: 1  TOP_RST_MISC: 1
pl pmic powerkey Release
[pmic6323_init] powerKey = 0
[pmic6323_init] is USB in = 0xB004
[pmic6323_init] Reg[0x11A]=0x1B
pmic setup LED
[pmic6323_init] Done...................
mt7623 disable long press reset ->>>>>
mt7623 disable long press reset <<<<<-
mt7623 VPA supplied by 1.0V to MT7530 ->
mt7623 VPA supplied by 1.0V to MT7530 <-
mt7623 enables RG_VGP1_EN for LCM ->
mt7623 enables RG_VGP1_EN for LCM <-
MT7623 E2 setting =>
MT7623 E2 setting <=
[PLFM] Init I2C: OK(0)
[PLFM] Init PWRAP: OK(0)
[PLFM] Init PMIC: OK(0)
[PLFM] chip[CA00]

[BLDR] [Support SD/eMMC] Build Time: 20170210-093340
==== Dump RGU Reg ========
RGU MODE:     4D
RGU LENGTH:   FFE0
RGU STA:      0
RGU INTERVAL: FFF
RGU SWSYSRST: 0
==== Dump RGU Reg End ====
RGU: g_rgu_satus:0
 mtk_wdt_mode_config  mode value=10, tmp:22000010
PL P ON
WDT does not trigger reboot
RGU mtk_wdt_init:MTK_WDT_DEBUG_CTL(590200F3)
kpd read addr: 0x0040: data:0x4001
Enter mtk_kpd_gpio_set! 
kpd debug column : 0, 0, 0, 0, 0, 0, 0, 0
kpd debug row : 0, 0, 0, 0, 0, 0, 0, 0
after set KP enable: KP_SEL = 0x0 !
MTK_PMIC_RST_KEY is used for this project!
[RTC] get_frequency_meter: input=0x0, ouput=5
[RTC] get_frequency_meter: input=0x0, ouput=3968
[RTC] get_frequency_meter: input=0x0, ouput=5
[RTC] get_frequency_meter: input=0x0, ouput=0
[RTC] get_frequency_meter: input=0x0, ouput=0
[RTC] bbpu = 0xD, con = 0x426
[RTC] powerkey1 = 0xA357, powerkey2 = 0x67D2
Writeif_unlock
[RTC] RTC_SPAR0=0x40 
rtc_2sec_reboot_check cali=1792
rtc_2sec_stat_clear
[RTC] irqsta = 0x0, pdn1 = 0x0, pdn2 = 0x201, spar0 = 0x40, spar1 = 0x800
[RTC] new_spare0 = 0x0, new_spare1 = 0x1, new_spare2 = 0x1, new_spare3 = 0x1
[RTC] bbpu = 0xD, con = 0x426, cali = 0x700
pl pmic powerkey Release
[PLFM] Power key boot!
[RTC] rtc_bbpu_power_on done
[EMI] mcp_dram_num:0,discrete_dram_num:1,enable_combo_dis:0
[EMI] PCDDR3
[Check]mt_get_mdl_number 0x0
[EMI] eMMC/NAND ID = 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
[EMI] MDL number = 0
[EMI] emi_set eMMC/NAND ID = 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
[EMI][Vcore]0x21E=0x48,0x220=0x48
[EMI][Vmem]0x554=0x0
wait for frequency meter finish, CLK26CALI = 0x81
[EMI] PCDDR3 DRAM Clock = 1333004 KHz, MEMPLL MODE = 2 
[EMI] PCDDR3 RXTDN Calibration:
Start REXTDN SW calibration...
drvp=0xB,drvn=0x9
[EMI] pinmux = 4
===============================================================================

        dramc_write_leveling_swcal
===============================================================================
delay  byte0  byte1  byte2  byte3
-----------------------------
0    0    0    0    0    
1    0    0    0    1    
2    0    0    1    1    
3    0    0    1    1    
4    0    1    1    1    
5    0    1    1    1    
6    0    1    1    1    
7    0    1    1    1    
8    1    1    1    1    
9    1    1    1    1    
10    1    1    1    1    
11    1    1    1    1    
12    1    1    1    1    
13    1    1    1    1    
14    1    1    1    1    
15    1    1    1    1    
pass bytecount = 4
byte_i    status    best delay
0    2    8
1    2    4
2    2    2
3    2    1
========================================
[write leveling]DQS: 0x1248, DQM: 0x1248
[write leveling after remap]DQ byte0 reg: 0x200 val: 0x88884444
[write leveling after remap]DQ byte1 reg: 0x204 val: 0x44448888
[write leveling after remap]DQ byte2 reg: 0x208 val: 0x22221111
[write leveling after remap]DQ byte3 reg: 0x20C val: 0x11112222
=============================================
X-axis: DQS Gating Window Delay (Fine Scale)
Y-axis: DQS Gating Window Delay (Coarse Scale)
=============================================
          0    8   16   24   32   40   48   56   64   72   80   88   96  104  112  120
      --------------------------------------------------------------------------------
0000:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0001:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0002:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0003:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0004:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0005:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0006:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0007:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0008:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0009:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
000A:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
000B:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
000C:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
000D:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
000E:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
000F:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0010:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0011:|    0    0    0    0    0    0    0    0    0    0    1    1    1    1    1    1
0012:|    0    0    0    1    1    1    1    1    1    1    1    1    1    1    1    0
0013:|    1    1    1    1    1    1    1    1    1    0    0    0    0    0    0    0
0014:|    1    1    1    0    0    0    0    0    0    0    0    0    0    0    0    0
0015:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0016:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0017:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0018:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
0019:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
001A:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
001B:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
001C:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
001D:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
001E:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
001F:|    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0
Rank 0 coarse tune value selection : 18, 18
18
64
rank 0 coarse = 18
rank 0 fine = 64
00:|    0    0    0    0    0    0    0    1    1    1    1    0
opt_dle value:12
==================================================================
                RX      DQS perbit delay software calibration 
==================================================================
1.0-31 bit dq delay value
==================================================================
bit|     0  1  2  3  4  5  6  7  8  9
--------------------------------------
0 |    0 0 0 0 0 0 0 0 0 0 
10 |    0 0 0 0 0 0 0 0 0 0 
20 |    0 0 0 0 0 0 0 0 0 0 
30 |    0 0 
--------------------------------------
==================================================================
2.dqs window
x=pass dqs delay value (min~max)center 
y=0-7bit DQ of every group
input delay:DQS0 =53 DQS1 = 46 DQS2 =57 DQS3 = 46
==================================================================
bit     DQS0     bit      DQS1     bit     DQS2     bit     DQS3
0  (19~80)49  8  (9~70)39  16  (21~78)49  24  (18~68)43
1  (21~80)50  9  (11~72)41  17  (22~79)50  25  (17~68)42
2  (21~78)49  10  (11~72)41  18  (24~80)52  26  (18~72)45
3  (19~78)48  11  (15~71)43  19  (21~76)48  27  (17~74)45
4  (23~82)52  12  (18~74)46  20  (25~82)53  28  (20~72)46
5  (22~78)50  13  (17~71)44  21  (23~80)51  29  (19~72)45
6  (22~80)51  14  (13~72)42  22  (25~80)52  30  (15~68)41
7  (23~83)53  15  (17~73)45  23  (27~87)57  31  (18~74)46
==================================================================
3.dq delay value last
==================================================================
bit|    0  1  2  3  4  5  6  7  8   9
--------------------------------------
0 |    4 3 4 5 1 3 2 0 7 5 
10 |    5 3 0 2 4 1 8 7 5 9 
20 |    4 6 5 0 3 4 1 1 0 1 
30 |    5 0 
==================================================================
*DQIDLY1 = 0x5040304
*DQIDLY2 = 0x20301
*DQIDLY3 = 0x3050507
*DQIDLY4 = 0x1040200
*DQIDLY5 = 0x9050708
*DQIDLY6 = 0x50604
*DQIDLY7 = 0x1010403
*DQIDLY8 = 0x50100
*DRAMC_R0DELDLY = 0x2E392E35

[MEM]CONA:F3A2,conf1:F07486A3
DM4BitMux = 1 
DQSO 0 in TX per-bit = 0 <= DQSO 0 in WL = 8  
DQSO 1 in TX per-bit = 0 <= DQSO 1 in WL = 4  
[Warning] DQSO 2 in TX per-bit = 6 > DQSO 2 in WL = 2  
[Warning] DQSO 3 in TX per-bit = 6 > DQSO 3 in WL = 1  
Tx DQM dly  = 0x2199
Tx DQM dly bit4 = 0x0
DRAMC_DQODLY1=99BB989Ah
DRAMC_DQODLY2=9A99B8AAh
DRAMC_DQODLY3=1103142h
DRAMC_DQODLY4=32102023h
Tx DQ dly bit4 = 0x0
Tx DQS dly = 0x6648
Tx DQS dly bit4 = 0x0
TX Byte0: DQ - 22, DQS - 18. win_sum= 39
TX Byte1: DQ - 25, DQS - 15. win_sum= 39
TX Byte2: DQ - 15, DQS - 25. win_sum= 39
TX Byte3: DQ - 14, DQS - 23. win_sum= 36
DRAMC calibration takes 653158332 CPU cycles

BPI: SD/eMMC SD=1 eMMC=0 id = 1 (drivers/mmc/mediatek/mtk_mmc.c)
__mmc_init ret = 0
ret2 = 1
ret2 = 1
BPI: g_mtk_mmc_block.dev = 1
<= [mmc1 block 0] =>
[0x00000000] 53 44 4d 4d 43 5f 42 4f
[0x00000008] 4f 54 00 00 01 00 00 00
[0x00000010] 00 02 00 00 ff ff ff ff
[0x00000018] ff ff ff ff ff ff ff ff
[0x00000020] ff ff ff ff ff ff ff ff
[0x00000028] ff ff ff ff ff ff ff ff
[0x00000030] ff ff ff ff ff ff ff ff
[0x00000038] ff ff ff ff ff ff ff ff
[0x00000040] ff ff ff ff ff ff ff ff
[0x00000048] ff ff ff ff ff ff ff ff
[0x00000050] ff ff ff ff ff ff ff ff
[0x00000058] ff ff ff ff ff ff ff ff
[0x00000060] ff ff ff ff ff ff ff ff
[0x00000068] ff ff ff ff ff ff ff ff
[0x00000070] ff ff ff ff ff ff ff ff
[0x00000078] ff ff ff ff ff ff ff ff
[0x00000080] ff ff ff ff ff ff ff ff
[0x00000088] ff ff ff ff ff ff ff ff
[0x00000090] ff ff ff ff ff ff ff ff
[0x00000098] ff ff ff ff ff ff ff ff
[0x000000a0] ff ff ff ff ff ff ff ff
[0x000000a8] ff ff ff ff ff ff ff ff
[0x000000b0] ff ff ff ff ff ff ff ff
[0x000000b8] ff ff ff ff ff ff ff ff
[0x000000c0] ff ff ff ff ff ff ff ff
[0x000000c8] ff ff ff ff ff ff ff ff
[0x000000d0] ff ff ff ff ff ff ff ff
[0x000000d8] ff ff ff ff ff ff ff ff
[0x000000e0] ff ff ff ff ff ff ff ff
[0x000000e8] ff ff ff ff ff ff ff ff
[0x000000f0] ff ff ff ff ff ff ff ff
[0x000000f8] ff ff ff ff ff ff ff ff
[0x00000100] ff ff ff ff ff ff ff ff
[0x00000108] ff ff ff ff ff ff ff ff
[0x00000110] ff ff ff ff ff ff ff ff
[0x00000118] ff ff ff ff ff ff ff ff
[0x00000120] ff ff ff ff ff ff ff ff
[0x00000128] ff ff ff ff ff ff ff ff
[0x00000130] ff ff ff ff ff ff ff ff
[0x00000138] ff ff ff ff ff ff ff ff
[0x00000140] ff ff ff ff ff ff ff ff
[0x00000148] ff ff ff ff ff ff ff ff
[0x00000150] ff ff ff ff ff ff ff ff
[0x00000158] ff ff ff ff ff ff ff ff
[0x00000160] ff ff ff ff ff ff ff ff
[0x00000168] ff ff ff ff ff ff ff ff
[0x00000170] ff ff ff ff ff ff ff ff
[0x00000178] ff ff ff ff ff ff ff ff
[0x00000180] ff ff ff ff ff ff ff ff
[0x00000188] ff ff ff ff ff ff ff ff
[0x00000190] ff ff ff ff ff ff ff ff
[0x00000198] ff ff ff ff ff ff ff ff
[0x000001a0] ff ff ff ff ff ff ff ff
[0x000001a8] ff ff ff ff ff ff ff ff
[0x000001b0] ff ff ff ff ff ff ff ff
[0x000001b8] cd d6 0e 00 00 00 00 be
[0x000001c0] 33 0c 0c 61 34 2d 00 20
[0x000001c8] 03 00 00 00 08 00 00 61
[0x000001d0] 35 2d 83 81 cb b6 00 20
[0x000001d8] 0b 00 00 e0 dd 00 00 00
[0x000001e0] 00 00 00 00 00 00 00 00
[0x000001e8] 00 00 00 00 00 00 00 00
[0x000001f0] 00 00 00 00 00 00 00 00
[0x000001f8] 00 00 00 00 00 00 55 aa

Partition Map for MMC device 1  --   Partition Type: DOS

Part    Start Sector    Num Sectors     UUID            Type
  1     204800          524288          000ed6cd-01     0c
  2     729088          14540800        000ed6cd-02     83
mmc1 is available
Interface:  MMC
  Device 1: Vendor: Man 000003 Snr 0610a701 Rev: 5.4 Prod: SC32G�
            Type: Removable Hard Disk
            Capacity: 30436.5 MB = 29.7 GB (62333952 x 512)
Filesystem: FAT16 "BPI-BOOT   "
Boot from SD
reading bananapi/bpi-r2/linux/uEnv.txt
771 bytes read in 7 ms (107.4 KiB/s)
Loaded environment from uEnv.txt
Banana Pi bpi-r2 chip: mt7623n Service: linux
reading bananapi/bpi-r2/linux/uImage
7515732 bytes read in 965 ms (7.4 MiB/s)
reading bananapi/berryboot.img
** Unable to read file bananapi/berryboot.img **
bootm flag=0, states=70f
## Booting kernel from Legacy Image at 84000000 ...
   Image Name:   Linux-4.4.70-BPI-R2-Kernel
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    7515668 Bytes = 7.2 MiB
   Load Address: 80008000
   Entry Point:  80008000
   Verifying Checksum ... OK
   Loading Kernel Image ... OK

Starting kernel ...

(Debian loads properly from SD card)

**Comment by dfiloni** [comment]
@fgheorghe : you have to install the LEDE image on the SD so you can access the
BPI**-R2**> (it's not BPI-IoT) prompt which will allow you to enter "emmc ...", the Ubuntu image is not good for this purpose.
Once you've executed the second command you can boot your Ubuntu SD and reinstall it, the LEDE image is needed only to get the right prompt to run the "emmc ..." commands.

**Comment by garywangcn** [comment]
I will add the emmc command to the uboot of this repo, and there is a command to change the partition configuration

**Comment by fgheorghe** [comment]
Tried downloading the image, getting this: Oh oh, the page you are visiting does not exist. from this URL: http://pan.baidu.com/s/1eS1pRCA

**Comment by garywangcn** [comment]
@fgheorghe this link is still available, can you please have a try?

Thanks

**Comment by fgheorghe** [comment]
Perfect - it worked! Thank you for your support! Now my last question is how to get HDMI to work? I had a look into script.fex, but no luck. What I am getting is a scrambled image (i.e.: something is on the screen, but unintelligible). Having the same issue with Ubuntu and Debian (jessie lite and XFCE desktop preview). Any clues? Thank you again.

**Comment by fgheorghe** [comment]
Odd, now ls /dev/mmcblk1 is gone, at least in Debian Jessie lite - used to show up.

**Comment by garywangcn** [comment]
https://github.com/BPI-SINOVOIP/BPI-R2-bsp/commit/71d865da906ea1f333b56bf810cb789bad2e8cac

This commit is to support emmc command in uboot.

**Comment by dfiloni** [comment]
@garywangcn : Hi Gary, I tested today (the kernel and uboot were rebuilt today too) and emmc command (from this repository) doesn't work for me, I had to use the LEDE image, do I have to edit anything in order to enable it?
